### ISSUE TITLE
reverse mode ?

### ISSUE THREAD

**Issue by gilra2000** [Flipkart/recyclerlistview#114]
Is it possible?

please

**Comment by naqvitalha** [comment]
Yes it is. It is actually very easy to do in any list. Use `ScaleY: -1` transform on the list post that do the same for all items being rendered. Let me know if this helps.

**Comment by naqvitalha** [comment]
Assuming this to be resolved. Closing.

**Comment by Haraldson** [comment]
It seems that this hack (flipping items upside down, then flipping the entire list back to normal) makes it so that the layouts of the items in the resulting visible area of the list (the end) is processed last, leaving me with items visually being stacked on top of each other for a few seconds.

Is there any progress on the built-in list reversal? It would be so helpful for interactive lists where time decides the order of items and where items should come up from the bottom, such as in a chat.

**Comment by Haraldson** [comment]
Furthermore, I guess what is now the last item visually, is actually the first item data-wise, and it causes re-renders as [described in the guides](https://github.com/Flipkart/recyclerlistview/tree/master/docs/guides/performance#4-ensure-shouldcomponentupdate-is-present) for all items _above_ it – which doesn’t really work with a chat-like list where items flow from the bottom and up.

**Comment by gagangoku** [comment]
+1

**Comment by gagangoku** [comment]
Please support a proper reverse mode. Otherwise this happens:
![Screenshot_20200313-032510](https://user-images.githubusercontent.com/544881/76570594-ac53a600-64db-11ea-9921-09ca854cd11a.jpg)

Not to mention the extra transforms causing entire list to be re-rendered if a new message is added (since its added at the beginning, not the end)

**Comment by MyFirstGitEver** [comment]
Can anyone provide me with reall code. What do you guys mean?
