### ISSUE TITLE
Further improvements for RNW

### ISSUE THREAD

**Issue by necolas** [Flipkart/recyclerlistview#137]
There are a few places where I think the implementation could work better with RNW. The "web" implementation may be OK for React DOM apps, but since it doesn't rely on RNW at all, it can't provide related functionality like automatic RTL layout flipping. The "react-native" implementation on web pulls in `Animated` which can add to the bundle size and runs animations on the main thread. I noticed some helpful ScrollView props like `scrollEnabled` are not available either.

## react-native implementation

**DefaultJSItemAnimator**

You could create a separate `.web.js` implementation that doesn't import `Animated` and instead relies on CSS transitions (as the `web` implementation does).

Related question: I'm not sure why there is a web-specific fork in this code. Why is native getting passed `left`/`top` props rather than a style prop?

```js
    private _getNativePropObject(x: number, y: number): object {
        const point = { left: x, top: y };
        return !IS_WEB ? point : { style: point };
    }
```

## web implementation

The layout of the wrapping divs in some components doesn't match RN, as they are not styled the same as the view flex containers.

**ScrollViewer.tsx**

Remove `componentWillMount` and replace `componentWillReceiveProps` with `componentDidUpdate`.

`scrollTo` can be smoother by relying on the browser's built-in smooth scrolling, which RNW relies on in `ScrollView`.

You might also want to include a caveat about using RNW + window scrolling + Touchable items. The Touchables expect to be in `ScrollView` to correctly transfer the responder to the scroller as needed.

**Comment by naqvitalha** [comment]
@necolas 
## Web vs RNW vs RN
There is hardly any difference between the web and the RNW implementation. The web version was initially created for pure web use. However, they both can be matched easily. I'll explain the problem:

Items in RN are positioned using left/top while in web using transforms. Using the former on web also introduces some extra layout overhead. It might be negligible but it is there. RN has no perf difference in RLV use case. So, if I have to use transforms in RNW I'll have to give up on the `onLayout` callback and call `measure` on `componentDidUpdate` instead. `measure` is again debounced causing even more lag. If only I could synchronously read the dimensions of given view then this would not be a problem. Is there an internal api to do that? Or do you think using left/top is okay for positioning and transitioning since the cells are positioned as absolute?

Another approach that has worked out well is using RLV web `ViewRenderers` inside RNW `ScrollView1. We can try this too.

We want to be able to switch to RNW without any issues. Not going going through the /web route is our goal too.

## react-native implementation
### DefaultJSItemAnimator
Agreed on the import part. Might be an issue for RNW users. We can get rid of `Animated` but the transitions will still happen on layout properties `left/top`. I can do the math and use transforms instead but that will break the `ItemAnimator` consistency.

Regarding the other question from what I've read in most of sample code you pass `left/top` directly to RN but in RNW you need to pass style. I didn't have the time benchmark the change so I played safe.

## web implementation
Styling can be different, I agree. Can you help us align the styling of those divs please? We will appreciate it.

`componentWillMount` helps incase of window scrolling, since layout of window remains constant I can simply avoid the single frame lag that would otherwise happen while rendering in a `ScrollView`.

`componentWillReceiveProps` is used because scroll listener needs to be changed on next render if `distanceFromWindow` has been updated.

Agreed on the `scrollTo` implementation. Will fix that. Btw in our current implementation with RNW smooth scrolling never happens was this added in recent versions of RNW `ScrollView`?

One problem that we are stuck at is the window scrolling part, the navigation bar in any browser doesn't hide with RNW implementation, how can we achieve that? Most browsers have made the assumption that window is always scrollable. Ideas?

## Summarizing
- Getting rid `Animated` by default in RNW use cases
- Align the styling of divs
- Smooth scrolling using CSS
- Figuring out WindowScrolling for RNW

**Comment by necolas** [comment]
I didn't understand the bit about transforms and onLayout.

I think browsers need to give developers the ability to control the browser nav bar. There is a proposal to let you define the root scroller other than body. Personally, I don't think it's that important to have the bar collapsing and focus should be on installed PWA use case. But there are other quirks on desktop browsers where scroll bars don't float over the UI and cause content to move

**Comment by naqvitalha** [comment]
Yeah it's a little difficult to understand. Simply put I would want to use `div` to wrap around `View`. That enables me to use transform for layout so it's worth it. Performance will be identical then. It would help if you can help me style it similar to a `View`.  If you're wondering why I'm not using `View` itself, that is because for my most optimal implementation I would need to observe dimensions of it synchronously. As of now that is not available in RNW, it would help if I can access it somehow. Maybe something that you can expose for supported libraries.

Regarding the window scrolling part that is a much bigger issue here in India since lot of people use browsers like UC that have not one but two onscreen bars. I wished web/RN has something like Android's coordinator layout.

**Comment by necolas** [comment]
Let's just not debounce layout calls in View.

I'd also mention your pain with the browser bars to the chrome and uc browser teams; it might help speed up efforts to provide developers with more control over that pattern.

**Comment by naqvitalha** [comment]
Removing debounce will still not allow me to use just transforms. You see onLayout only fires while changing left/top/height/width. I'll try the `div` approach first and see how it goes. Seems like a harmless abstraction, onLayout anyway doesn't work on resize (on web). So, there is nothing to lose. Thoughts?

**Comment by naqvitalha** [comment]
@necolas check this PR: https://github.com/Flipkart/recyclerlistview/pull/140. This will bridge the gap in performance. Let me know your thoughts

**Comment by necolas** [comment]
I think the RNW part needs to be using `View`

**Comment by naqvitalha** [comment]
Eventually yes. First onLayout needs to be figured out to justify the performance cost. Anyways, the current implementation is working pretty well performance wise. Btw since everything is proxied through `setNativeProps` don't you think you should try running it on a worker? Compute one frame early, I think the perf results will be amazing

**Comment by naqvitalha** [comment]
Most of these are solved in v2. Closing.
