### ISSUE TITLE
RecyclerListView repeating data after position 2

### ISSUE THREAD

**Issue by Prerna11082** [Flipkart/recyclerlistview#177]
Hi,
I've been trying to use this component in my app.
I have a lot of text for display. And it is dynamic, so I've set forceNonDeterministicRendering=true. And also since most of the list items have a lot of text to render, so I've added estimated height of full device height in layout provider.
The first and second element renders fine. But after that, data is repeating, instead of the third element, it is displaying data from first element.
I have reproduced the issue on expo.
Link: https://snack.expo.io/@prernasingh/recyclerviewtest

Please help in fixing this issue.

**Comment by naqvitalha** [comment]
@Prerna11082 `RecyclerListView` reuses components rather than creating/destroying like `VirtualizedList`. I have fixed your implementation here: https://snack.expo.io/HJRQm2_Cf
Inside `VerseViewBook` you were relying on constructor so update state which is called once. Relying on props instead fixes the problem.

**Comment by uday5162** [comment]
Hello @naqvitalha,
I am also facing the similar issue, I have tried fixing by your implementation but it doesn't work.
The component inside rowRender method has setState in componentDidMount  is that a problem?
