### ISSUE TITLE
Row changes does not carry the Props and states with it

### ISSUE THREAD

**Issue by Louies89** [Flipkart/recyclerlistview#200]
Hi @naqvitalha,
I am making a chat application with realm db, so when ever db is updated with a new message, the list of chats from different users shall be re-ordered according to the messages received time in descending order as WhatsApp does

I am able to update the row positions according to the db update. But there are problem when the position of a row has changed.

Example:
Suppose rows are in below order:'

Person A's Chat row (Containing props and stated of Person A)
Person B's Chat row (Containing props and stated of Person B)
Person C's Chat row (Containing props and stated of Person C)

now if person B sends a message the chat list shall be re rendered and it shall be shown as below, but the props and states are remaining same.

Person B's Chat row (Containing props and stated of Person A)
Person A's Chat row (Containing props and stated of Person B)
Person C's Chat row (Containing props and stated of Person C)

So next time if any event is send to Person B's Chat, it is not updating it as we have implemented `shouldComponentUpdate ` checks.

My data Provider is as below:
`new DataProvider((r1, r2) => { return r1.id !== r2.id }).cloneWithRows(this.state.chats)`
(ids are unique)
So how each row should carry its props? If I have to use `rowHasChanged` I do not understand how to implement that and the sample examples does not have any example regarding that.

Please help me..

**Comment by naqvitalha** [comment]
Props will be consistent `state` however can get lost. RecyclerListView can reuse cells to render any items the way it sees fit. Thus you cannot rely on state. Can you share your `rowRenderer`? You shouldn't be running into this issue. You can assign separate types to both person entities etc or use stableIds.
Why do you need state inside your cell? I would strongly discourage that.

**Comment by naqvitalha** [comment]
If `ChatList` has a data aware state then it will be a problem during recycling. Why can't you pass the unread count as a prop externally just like other props?
Maybe I'm not understanding the use case. Can you provide an expo snack for me to look into?

**Comment by Louies89** [comment]
As I am working with realm db, cant make a expo example to make it work.
I understand what you saying... I will try it and let you know. :)

**Comment by Louies89** [comment]
And if there are cells whose props are same as before, then while refreshing the dataProvider, all those cells re-render or not?

**Comment by naqvitalha** [comment]
I think what you're looking for is the `extendedState` prop. You can keep page level stuff here that affects all rows. Changing extended state re renders everything. Make sure you change it only when necessary.

**Comment by Louies89** [comment]
I used that, but do not want to use that, as it e renders everything...

**Comment by tafelito** [comment]
@naqvitalha I'm not sure if the issue I'm having is similar to this one or not. I'm trying to remove items from a list and before an item gets deleted, there is an animation that scales down the row. The problem is that after the animation is run and the data is updated, if I removed row A, then row B will re use row A and because row A was scaled down, now row B is not shown.

here is a quick demo

https://codesandbox.io/s/4j38w51ql7

I tried using `optimizeForInsertDeleteAnimations` or even `disableRecycling` and none of that worked. 

I had to set the `getStableIds` to get it to work, but I thought that `optimizeForInsertDeleteAnimations` was meant for that

**Comment by arunreddy-flipkart** [comment]
Local states will cause issues with recycling because when a component is recycled, it is not unmounted but instead only updated with the new data. The older state will therefore persist in the new item and lead to unpredictable behaviour. You could store such state at a parent level and pass it down as a prop or use the extendedState prop but make a note to not change extendedState too frequently for performance reasons.

**Comment by maxakak1998** [comment]
> Local states will cause issues with recycling because when a component is recycled, it is not unmounted but instead only updated with the new data. The older state will therefore persist in the new item and lead to unpredictable behaviour. You could store such state at a parent level and pass it down as a prop or use the extendedState prop but make a note to not change extendedState too frequently for performance reasons.

https://github.com/Flipkart/recyclerlistview/issues/432
