### ISSUE TITLE
Excessive calls to LayoutProvider methods because no  'shouldComponentUpdate' implemented

### ISSUE THREAD

**Issue by DaveLomber** [Flipkart/recyclerlistview#411]
Hi there 

I had debugged the src code of RecyclerListView.tsx
and found the case that every time my parent component gets a 'render' call (where I render a RecyclerListView), then I'm getting the calls to LayoutProvider methods to get a type & dims. 

I found it comes from here
https://github.com/Flipkart/recyclerlistview/blob/master/src/core/RecyclerListView.tsx#L367

renderCompat -> _generateRenderStack -> _renderRowUsingMeta -> this._virtualRenderer.syncAndGetKey

but the data is returned from LayoutProvider methods are the same, 
so I think it's the excessive calls 

Is there any reason not to implementing a 'shouldComponentUpdate' for RecyclerListView ?
Or is there any other way to optimize it?

thanks

**Comment by arunreddy-flipkart** [comment]
Hi,

The LayoutProvider methods are called at each render for each item in the recylerlistview in order to get the dimensions of the layout for rendering. The shouldComponentUpdate has been implemented at the item level in the BaseViewRenderer.tsx to prevent unnecessary renders. Ideally, the recylerlistview should render every time the dataProvider has been changed. So, You could implement a shouldComponentUpdate in the parent component ( where the recyclerlistview is rendered) and trigger the render only if the data has changed.
