### ISSUE TITLE
Recyclerlistview in middle of the page make scroll to only the listview not for full page

### ISSUE THREAD

**Issue by thamizh82** [Flipkart/recyclerlistview#81]
I am using Recyclerlistview for my page, which is having first half with other functionality for site.
Then am using Recyclerlistview for data to render.

After integration the page scroll happens only to Recyclerlistview itself.  And only 10% of Recyclerlistview are visible.

How to make my entire page to scroll to view my full Recyclerlistview.
![flipkattest](https://user-images.githubusercontent.com/17337993/33254819-9cd57612-d370-11e7-96ca-0e8a895175d2.png)

**Comment by thamizh82** [comment]
Team,

Kindly reply soon pls....

**Comment by naqvitalha** [comment]
This looks like something from Android's Coordinator layout domain. There is no direct solution to achieve this right now since nested scrolling is a mess in react native. We'll need to build something similar to coordinator layout.

Check out the following links:
https://github.com/mohtada-h/react-native-nested-scrollview
https://github.com/facebook/react-native/issues/8024

Let us know if you find anything. It'll help everyone.

**Comment by naqvitalha** [comment]
Inactive for a while, closing.

**Comment by thamizh82** [comment]
I solved this issue by appending dummy header content to the result data.
e.g 
var headerData = [{ 'headerData': 'dummytext' }];
var outputData = headerData .concat(resultsetData);

In Recyclerview 
rowRenderer=this._renderRow;

_renderRow(type, data) {
    if (data.headerData == 'dummytext') {
         return (<View>Your header content</View>)
    }
    return return (<View>Your real data</View>)
}

**Comment by JhowEMK** [comment]
any news ?
