### ISSUE TITLE
onVisibleIndexesChanged misbehaves when a ViewType is taller than the window's height

### ISSUE THREAD

**Issue by AbdallaMohamed** [Flipkart/recyclerlistview#83]
I'm getting wrong values from onVisibleIndexesChanged. It's returning an empty array sometimes.

I reproduced it in a snack.
https://snack.expo.io/@abdallamohamed/recyclerlistview-onvisibleindexeschanged-bug

You can see the bug when you're scrolling through the list.

![nov-29-2017 15-48-11](https://user-images.githubusercontent.com/10912145/33380920-de7ea252-d51c-11e7-903c-02a7d2c50006.gif)

**Comment by naqvitalha** [comment]
I looked at your expo sample, I actually noticed something strange. The bottom `<Text/>` is inside a `<ScrollView/>` and when the page renders the listview is mounted with a much smaller height and then it resizes. I guess it has something to do with how ScrollView's layout happens. If I change that to a `<View/>` it works fine. Link: https://snack.expo.io/BJ7weO3lM
For RecyclerListView to handle height changes `canChangeSize` needs to be set to `true`.
But the title of this issue is the right one, ViewabilityTracker will mess up visibility callback if  item is larger than the window. I'll mark this as a bug, nice catch!

**Comment by AbdallaMohamed** [comment]
My bad, I was going to have the bottom scrollview as a log where I keep adding more lines for every time the onVisibleIndexesChanged callback is fired, but then I just decided to replace the text instead of appending to it.

For now, I made sure that none of my view types have a height larger than the window height. As a workaround until the bug is fixed. 

And by the way, I'm considering supporting both screen orientations in my app soon. Does that mean I need to set canChangeSize to true for the RecyclerListView so that it handles screen height changes?

**Comment by naqvitalha** [comment]
@AbdallaMohamed Yes you'll have to set `canChangeSize={true}`. The best part about orientation changes with RecyclerListView is that your firstVisibleIndex will get preserved automatically!

**Comment by naqvitalha** [comment]
@AbdallaMohamed Can you check `v1.2.6-beta.4`? See if that fixes your issue.

**Comment by naqvitalha** [comment]
Fixed, closing
