### ISSUE TITLE
when set forceNonDeterministicRendering={true}, mistake in performance occurred :(

### ISSUE THREAD

**Issue by hasanal1995** [Flipkart/recyclerlistview#91]
when set forceNonDeterministicRendering={true}, mistake in performance occurred :(, but i cannot set it to false; because layout will be damaged, any one can help??

this without forceNonDeterministicRendering but performance is high.
![43d6a89a-1569-47de-a33f-3f81d01c0055](https://user-images.githubusercontent.com/32715055/34078553-50e24586-e325-11e7-9215-358a44d8c610.jpeg).
and this with forceNonDeterministicRendering, layout is awesome but performance is poor
![85dce042-553f-4ffe-b498-7ffc31c88345](https://user-images.githubusercontent.com/32715055/34078598-c448f240-e325-11e7-9f59-83ec1781cb2d.jpeg)

any idea ??

**Comment by naqvitalha** [comment]
You layout looks deterministic to me. All items seem to be of fixed size. In any case, non deterministic shouldn't be much slower. There could be three things which are wrong:
1) Estimates dimensions are nowhere near the actual ones. This seems to be the case since your deterministic render looks way different.
2) Missing `shouldComponentUpdate` in your component which the `rowRenderer` returns. Very important for non deterministic scenario.
3) `rowHasChanged` in dataProvider has an invalid check that returns true most of the time. Most likely this is not the problem since deterministic mode is fast for you.

**Comment by hasanal1995** [comment]
please clarify, what is role of shouldComponentUpdate, rowRender, and rowHasChanged in performance of RecyclerView?
again, thank you very much

**Comment by naqvitalha** [comment]
In case of non deterministic rendering RecyclerListView will render a few times for than regular. These cycles are to reposition items after actual render. Since the whole tree will re-render with the listview `rowHasChanged` and `shouldComponentUpdate` make sure that your items don't. RecyclerListViews self render is pretty cheap. Having these checks prevents your item from being rendered unnecessarily which significantly reduces JS overhead.

**Comment by naqvitalha** [comment]
Inactive for a while. Closing.
