### ISSUE TITLE
ScrollEnabled property?

### ISSUE THREAD

**Issue by SudoPlz** [Flipkart/recyclerlistview#92]
Hey there,

I was wondering if I can disable scrolling, i.e with a `scrollEnabled={false}` prop

Thank you.

**Comment by naqvitalha** [comment]
Yes, you can. All `ScrollView` props work.

**Comment by SudoPlz** [comment]
You're the best, thank you. I'm working on your implementation right now, trying to figure everything out.
Thanks for making this list.

**Comment by naqvitalha** [comment]
I will prefer GitHub. But I do understand the need for slack.. I have created a new workspace https://join.slack.com/t/recyclerlistview/shared_invite/enQtMjkwMTc0MTEwNjI2LTYzNTllZmVlNzU1YzEwODQyMzU0ZjhlN2ExNjA3NzEwNzM1ZTQ0MmQyMWUxMTdmMmJjOTI2ZTgzMzJjY2JkYWI
But prefer git since it helps the community more.

**Comment by shivam-kumarthakur** [comment]
scrollEnabled={false} dosn't work in my code
